apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-wtmfp
    field.cattle.io/description: assignment2
  creationTimestamp: '2023-10-06T18:53:58Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 3
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.7.8-secret-migrator
      operation: Update
      time: '2023-10-06T18:53:59Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:etcdSnapshotCreate:
              .: {}
              f:generation: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePoolDefaults: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2023-10-06T20:44:30Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2023-10-06T20:44:31Z'
  name: k8-cluster
  namespace: fleet-default
  resourceVersion: '64684'
  uid: e01cf485-8bf3-49b3-9098-1b7694d52958
spec:
  kubernetesVersion: v1.26.8+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    etcdSnapshotCreate:
      generation: 1
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: k8-cluster-kubeconfig
  clusterName: c-m-bqjbl4qv
  conditions:
    - lastUpdateTime: '2023-10-06T18:58:31Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-10-06T18:53:58Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-10-06T20:44:30Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-10-06T20:44:31Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-10-06T18:53:58Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-10-06T18:53:59Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-10-06T18:53:59Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-10-06T18:53:59Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2023-10-06T20:44:31Z'
      message: waiting for etcd snapshot on node ip-172-31-87-222
      reason: Waiting
      status: Unknown
      type: Updated
    - lastUpdateTime: '2023-10-06T20:44:31Z'
      message: waiting for etcd snapshot on node ip-172-31-87-222
      reason: Waiting
      status: Unknown
      type: Provisioned
    - lastUpdateTime: '2023-10-06T18:58:34Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-10-06T18:54:01Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-10-06T18:58:16Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-10-06T18:54:03Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2023-10-06T18:58:02Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-10-06T18:58:08Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-10-06T18:58:11Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2023-10-06T18:58:31Z'
      status: 'True'
      type: Waiting
  observedGeneration: 3
  ready: true
